// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SenderMsg.proto

package com.laiyz.proto;

public final class SenderMsg {
  private SenderMsg() {}
  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
            (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ReqOrBuilder extends
          // @@protoc_insertion_point(interface_extends:com.laiyz.proto.Req)
          com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
    getIdBytes();

    /**
     * <code>string cmd = 2;</code>
     * @return The cmd.
     */
    java.lang.String getCmd();
    /**
     * <code>string cmd = 2;</code>
     * @return The bytes for cmd.
     */
    com.google.protobuf.ByteString
    getCmdBytes();

    /**
     * <code>string filepath = 3;</code>
     * @return The filepath.
     */
    java.lang.String getFilepath();
    /**
     * <code>string filepath = 3;</code>
     * @return The bytes for filepath.
     */
    com.google.protobuf.ByteString
    getFilepathBytes();

    /**
     * <code>uint64 ts = 4;</code>
     * @return The ts.
     */
    long getTs();

    /**
     * <code>uint64 accessFilePosition = 5;</code>
     * @return The accessFilePosition.
     */
    long getAccessFilePosition();
  }
  /**
   * Protobuf type {@code com.laiyz.proto.Req}
   */
  public  static final class Req extends
          com.google.protobuf.GeneratedMessageV3 implements
          // @@protoc_insertion_point(message_implements:com.laiyz.proto.Req)
          ReqOrBuilder {
    private static final long serialVersionUID = 0L;
    // Use Req.newBuilder() to construct.
    private Req(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Req() {
      id_ = "";
      cmd_ = "";
      filepath_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
            UnusedPrivateParameter unused) {
      return new Req();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Req(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
              com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              cmd_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              filepath_ = s;
              break;
            }
            case 32: {

              ts_ = input.readUInt64();
              break;
            }
            case 40: {

              accessFilePosition_ = input.readUInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                      input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
                e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return com.laiyz.proto.SenderMsg.internal_static_com_laiyz_proto_Req_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return com.laiyz.proto.SenderMsg.internal_static_com_laiyz_proto_Req_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      com.laiyz.proto.SenderMsg.Req.class, com.laiyz.proto.SenderMsg.Req.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
    getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CMD_FIELD_NUMBER = 2;
    private volatile java.lang.Object cmd_;
    /**
     * <code>string cmd = 2;</code>
     * @return The cmd.
     */
    public java.lang.String getCmd() {
      java.lang.Object ref = cmd_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cmd_ = s;
        return s;
      }
    }
    /**
     * <code>string cmd = 2;</code>
     * @return The bytes for cmd.
     */
    public com.google.protobuf.ByteString
    getCmdBytes() {
      java.lang.Object ref = cmd_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        cmd_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FILEPATH_FIELD_NUMBER = 3;
    private volatile java.lang.Object filepath_;
    /**
     * <code>string filepath = 3;</code>
     * @return The filepath.
     */
    public java.lang.String getFilepath() {
      java.lang.Object ref = filepath_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        filepath_ = s;
        return s;
      }
    }
    /**
     * <code>string filepath = 3;</code>
     * @return The bytes for filepath.
     */
    public com.google.protobuf.ByteString
    getFilepathBytes() {
      java.lang.Object ref = filepath_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        filepath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TS_FIELD_NUMBER = 4;
    private long ts_;
    /**
     * <code>uint64 ts = 4;</code>
     * @return The ts.
     */
    public long getTs() {
      return ts_;
    }

    public static final int ACCESSFILEPOSITION_FIELD_NUMBER = 5;
    private long accessFilePosition_;
    /**
     * <code>uint64 accessFilePosition = 5;</code>
     * @return The accessFilePosition.
     */
    public long getAccessFilePosition() {
      return accessFilePosition_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (!getCmdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, cmd_);
      }
      if (!getFilepathBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, filepath_);
      }
      if (ts_ != 0L) {
        output.writeUInt64(4, ts_);
      }
      if (accessFilePosition_ != 0L) {
        output.writeUInt64(5, accessFilePosition_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (!getCmdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, cmd_);
      }
      if (!getFilepathBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, filepath_);
      }
      if (ts_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
                .computeUInt64Size(4, ts_);
      }
      if (accessFilePosition_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
                .computeUInt64Size(5, accessFilePosition_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof com.laiyz.proto.SenderMsg.Req)) {
        return super.equals(obj);
      }
      com.laiyz.proto.SenderMsg.Req other = (com.laiyz.proto.SenderMsg.Req) obj;

      if (!getId()
              .equals(other.getId())) return false;
      if (!getCmd()
              .equals(other.getCmd())) return false;
      if (!getFilepath()
              .equals(other.getFilepath())) return false;
      if (getTs()
              != other.getTs()) return false;
      if (getAccessFilePosition()
              != other.getAccessFilePosition()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + CMD_FIELD_NUMBER;
      hash = (53 * hash) + getCmd().hashCode();
      hash = (37 * hash) + FILEPATH_FIELD_NUMBER;
      hash = (53 * hash) + getFilepath().hashCode();
      hash = (37 * hash) + TS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
              getTs());
      hash = (37 * hash) + ACCESSFILEPOSITION_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
              getAccessFilePosition());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.laiyz.proto.SenderMsg.Req parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.laiyz.proto.SenderMsg.Req parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.laiyz.proto.SenderMsg.Req parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.laiyz.proto.SenderMsg.Req parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.laiyz.proto.SenderMsg.Req parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.laiyz.proto.SenderMsg.Req parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.laiyz.proto.SenderMsg.Req parseFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }
    public static com.laiyz.proto.SenderMsg.Req parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.laiyz.proto.SenderMsg.Req parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.laiyz.proto.SenderMsg.Req parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.laiyz.proto.SenderMsg.Req parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }
    public static com.laiyz.proto.SenderMsg.Req parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.laiyz.proto.SenderMsg.Req prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
              ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.laiyz.proto.Req}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:com.laiyz.proto.Req)
            com.laiyz.proto.SenderMsg.ReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return com.laiyz.proto.SenderMsg.internal_static_com_laiyz_proto_Req_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
        return com.laiyz.proto.SenderMsg.internal_static_com_laiyz_proto_Req_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        com.laiyz.proto.SenderMsg.Req.class, com.laiyz.proto.SenderMsg.Req.Builder.class);
      }

      // Construct using com.laiyz.proto.SenderMsg.Req.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
              com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = "";

        cmd_ = "";

        filepath_ = "";

        ts_ = 0L;

        accessFilePosition_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
      getDescriptorForType() {
        return com.laiyz.proto.SenderMsg.internal_static_com_laiyz_proto_Req_descriptor;
      }

      @java.lang.Override
      public com.laiyz.proto.SenderMsg.Req getDefaultInstanceForType() {
        return com.laiyz.proto.SenderMsg.Req.getDefaultInstance();
      }

      @java.lang.Override
      public com.laiyz.proto.SenderMsg.Req build() {
        com.laiyz.proto.SenderMsg.Req result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.laiyz.proto.SenderMsg.Req buildPartial() {
        com.laiyz.proto.SenderMsg.Req result = new com.laiyz.proto.SenderMsg.Req(this);
        result.id_ = id_;
        result.cmd_ = cmd_;
        result.filepath_ = filepath_;
        result.ts_ = ts_;
        result.accessFilePosition_ = accessFilePosition_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
              com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
              com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.laiyz.proto.SenderMsg.Req) {
          return mergeFrom((com.laiyz.proto.SenderMsg.Req)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.laiyz.proto.SenderMsg.Req other) {
        if (other == com.laiyz.proto.SenderMsg.Req.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (!other.getCmd().isEmpty()) {
          cmd_ = other.cmd_;
          onChanged();
        }
        if (!other.getFilepath().isEmpty()) {
          filepath_ = other.filepath_;
          onChanged();
        }
        if (other.getTs() != 0L) {
          setTs(other.getTs());
        }
        if (other.getAccessFilePosition() != 0L) {
          setAccessFilePosition(other.getAccessFilePosition());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        com.laiyz.proto.SenderMsg.Req parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.laiyz.proto.SenderMsg.Req) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       * @return The id.
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
      getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {

        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object cmd_ = "";
      /**
       * <code>string cmd = 2;</code>
       * @return The cmd.
       */
      public java.lang.String getCmd() {
        java.lang.Object ref = cmd_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          cmd_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string cmd = 2;</code>
       * @return The bytes for cmd.
       */
      public com.google.protobuf.ByteString
      getCmdBytes() {
        java.lang.Object ref = cmd_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          cmd_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string cmd = 2;</code>
       * @param value The cmd to set.
       * @return This builder for chaining.
       */
      public Builder setCmd(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        cmd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string cmd = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCmd() {

        cmd_ = getDefaultInstance().getCmd();
        onChanged();
        return this;
      }
      /**
       * <code>string cmd = 2;</code>
       * @param value The bytes for cmd to set.
       * @return This builder for chaining.
       */
      public Builder setCmdBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        cmd_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object filepath_ = "";
      /**
       * <code>string filepath = 3;</code>
       * @return The filepath.
       */
      public java.lang.String getFilepath() {
        java.lang.Object ref = filepath_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          filepath_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string filepath = 3;</code>
       * @return The bytes for filepath.
       */
      public com.google.protobuf.ByteString
      getFilepathBytes() {
        java.lang.Object ref = filepath_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          filepath_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string filepath = 3;</code>
       * @param value The filepath to set.
       * @return This builder for chaining.
       */
      public Builder setFilepath(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        filepath_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string filepath = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearFilepath() {

        filepath_ = getDefaultInstance().getFilepath();
        onChanged();
        return this;
      }
      /**
       * <code>string filepath = 3;</code>
       * @param value The bytes for filepath to set.
       * @return This builder for chaining.
       */
      public Builder setFilepathBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        filepath_ = value;
        onChanged();
        return this;
      }

      private long ts_ ;
      /**
       * <code>uint64 ts = 4;</code>
       * @return The ts.
       */
      public long getTs() {
        return ts_;
      }
      /**
       * <code>uint64 ts = 4;</code>
       * @param value The ts to set.
       * @return This builder for chaining.
       */
      public Builder setTs(long value) {

        ts_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 ts = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearTs() {

        ts_ = 0L;
        onChanged();
        return this;
      }

      private long accessFilePosition_ ;
      /**
       * <code>uint64 accessFilePosition = 5;</code>
       * @return The accessFilePosition.
       */
      public long getAccessFilePosition() {
        return accessFilePosition_;
      }
      /**
       * <code>uint64 accessFilePosition = 5;</code>
       * @param value The accessFilePosition to set.
       * @return This builder for chaining.
       */
      public Builder setAccessFilePosition(long value) {

        accessFilePosition_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 accessFilePosition = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearAccessFilePosition() {

        accessFilePosition_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.laiyz.proto.Req)
    }

    // @@protoc_insertion_point(class_scope:com.laiyz.proto.Req)
    private static final com.laiyz.proto.SenderMsg.Req DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.laiyz.proto.SenderMsg.Req();
    }

    public static com.laiyz.proto.SenderMsg.Req getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Req>
            PARSER = new com.google.protobuf.AbstractParser<Req>() {
      @java.lang.Override
      public Req parsePartialFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return new Req(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Req> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Req> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.laiyz.proto.SenderMsg.Req getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RspOrBuilder extends
          // @@protoc_insertion_point(interface_extends:com.laiyz.proto.Rsp)
          com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
    getIdBytes();

    /**
     * <code>string cmd = 2;</code>
     * @return The cmd.
     */
    java.lang.String getCmd();
    /**
     * <code>string cmd = 2;</code>
     * @return The bytes for cmd.
     */
    com.google.protobuf.ByteString
    getCmdBytes();

    /**
     * <code>string filepath = 3;</code>
     * @return The filepath.
     */
    java.lang.String getFilepath();
    /**
     * <code>string filepath = 3;</code>
     * @return The bytes for filepath.
     */
    com.google.protobuf.ByteString
    getFilepathBytes();

    /**
     * <code>uint64 fileSize = 4;</code>
     * @return The fileSize.
     */
    long getFileSize();

    /**
     * <code>string checksum = 5;</code>
     * @return The checksum.
     */
    java.lang.String getChecksum();
    /**
     * <code>string checksum = 5;</code>
     * @return The bytes for checksum.
     */
    com.google.protobuf.ByteString
    getChecksumBytes();

    /**
     * <code>uint64 recvSize = 6;</code>
     * @return The recvSize.
     */
    long getRecvSize();

    /**
     * <code>uint64 currRecvSize = 7;</code>
     * @return The currRecvSize.
     */
    long getCurrRecvSize();

    /**
     * <code>uint64 reqTs = 8;</code>
     * @return The reqTs.
     */
    long getReqTs();

    /**
     * <code>uint64 rspTs = 9;</code>
     * @return The rspTs.
     */
    long getRspTs();

    /**
     * <code>uint64 accessFilePosition = 10;</code>
     * @return The accessFilePosition.
     */
    long getAccessFilePosition();
  }
  /**
   * Protobuf type {@code com.laiyz.proto.Rsp}
   */
  public  static final class Rsp extends
          com.google.protobuf.GeneratedMessageV3 implements
          // @@protoc_insertion_point(message_implements:com.laiyz.proto.Rsp)
          RspOrBuilder {
    private static final long serialVersionUID = 0L;
    // Use Rsp.newBuilder() to construct.
    private Rsp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Rsp() {
      id_ = "";
      cmd_ = "";
      filepath_ = "";
      checksum_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
            UnusedPrivateParameter unused) {
      return new Rsp();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Rsp(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
              com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              cmd_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              filepath_ = s;
              break;
            }
            case 32: {

              fileSize_ = input.readUInt64();
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              checksum_ = s;
              break;
            }
            case 48: {

              recvSize_ = input.readUInt64();
              break;
            }
            case 56: {

              currRecvSize_ = input.readUInt64();
              break;
            }
            case 64: {

              reqTs_ = input.readUInt64();
              break;
            }
            case 72: {

              rspTs_ = input.readUInt64();
              break;
            }
            case 80: {

              accessFilePosition_ = input.readUInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                      input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
                e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return com.laiyz.proto.SenderMsg.internal_static_com_laiyz_proto_Rsp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return com.laiyz.proto.SenderMsg.internal_static_com_laiyz_proto_Rsp_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      com.laiyz.proto.SenderMsg.Rsp.class, com.laiyz.proto.SenderMsg.Rsp.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
    getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CMD_FIELD_NUMBER = 2;
    private volatile java.lang.Object cmd_;
    /**
     * <code>string cmd = 2;</code>
     * @return The cmd.
     */
    public java.lang.String getCmd() {
      java.lang.Object ref = cmd_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cmd_ = s;
        return s;
      }
    }
    /**
     * <code>string cmd = 2;</code>
     * @return The bytes for cmd.
     */
    public com.google.protobuf.ByteString
    getCmdBytes() {
      java.lang.Object ref = cmd_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        cmd_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FILEPATH_FIELD_NUMBER = 3;
    private volatile java.lang.Object filepath_;
    /**
     * <code>string filepath = 3;</code>
     * @return The filepath.
     */
    public java.lang.String getFilepath() {
      java.lang.Object ref = filepath_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        filepath_ = s;
        return s;
      }
    }
    /**
     * <code>string filepath = 3;</code>
     * @return The bytes for filepath.
     */
    public com.google.protobuf.ByteString
    getFilepathBytes() {
      java.lang.Object ref = filepath_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        filepath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FILESIZE_FIELD_NUMBER = 4;
    private long fileSize_;
    /**
     * <code>uint64 fileSize = 4;</code>
     * @return The fileSize.
     */
    public long getFileSize() {
      return fileSize_;
    }

    public static final int CHECKSUM_FIELD_NUMBER = 5;
    private volatile java.lang.Object checksum_;
    /**
     * <code>string checksum = 5;</code>
     * @return The checksum.
     */
    public java.lang.String getChecksum() {
      java.lang.Object ref = checksum_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        checksum_ = s;
        return s;
      }
    }
    /**
     * <code>string checksum = 5;</code>
     * @return The bytes for checksum.
     */
    public com.google.protobuf.ByteString
    getChecksumBytes() {
      java.lang.Object ref = checksum_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        checksum_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RECVSIZE_FIELD_NUMBER = 6;
    private long recvSize_;
    /**
     * <code>uint64 recvSize = 6;</code>
     * @return The recvSize.
     */
    public long getRecvSize() {
      return recvSize_;
    }

    public static final int CURRRECVSIZE_FIELD_NUMBER = 7;
    private long currRecvSize_;
    /**
     * <code>uint64 currRecvSize = 7;</code>
     * @return The currRecvSize.
     */
    public long getCurrRecvSize() {
      return currRecvSize_;
    }

    public static final int REQTS_FIELD_NUMBER = 8;
    private long reqTs_;
    /**
     * <code>uint64 reqTs = 8;</code>
     * @return The reqTs.
     */
    public long getReqTs() {
      return reqTs_;
    }

    public static final int RSPTS_FIELD_NUMBER = 9;
    private long rspTs_;
    /**
     * <code>uint64 rspTs = 9;</code>
     * @return The rspTs.
     */
    public long getRspTs() {
      return rspTs_;
    }

    public static final int ACCESSFILEPOSITION_FIELD_NUMBER = 10;
    private long accessFilePosition_;
    /**
     * <code>uint64 accessFilePosition = 10;</code>
     * @return The accessFilePosition.
     */
    public long getAccessFilePosition() {
      return accessFilePosition_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (!getCmdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, cmd_);
      }
      if (!getFilepathBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, filepath_);
      }
      if (fileSize_ != 0L) {
        output.writeUInt64(4, fileSize_);
      }
      if (!getChecksumBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, checksum_);
      }
      if (recvSize_ != 0L) {
        output.writeUInt64(6, recvSize_);
      }
      if (currRecvSize_ != 0L) {
        output.writeUInt64(7, currRecvSize_);
      }
      if (reqTs_ != 0L) {
        output.writeUInt64(8, reqTs_);
      }
      if (rspTs_ != 0L) {
        output.writeUInt64(9, rspTs_);
      }
      if (accessFilePosition_ != 0L) {
        output.writeUInt64(10, accessFilePosition_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (!getCmdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, cmd_);
      }
      if (!getFilepathBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, filepath_);
      }
      if (fileSize_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
                .computeUInt64Size(4, fileSize_);
      }
      if (!getChecksumBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, checksum_);
      }
      if (recvSize_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
                .computeUInt64Size(6, recvSize_);
      }
      if (currRecvSize_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
                .computeUInt64Size(7, currRecvSize_);
      }
      if (reqTs_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
                .computeUInt64Size(8, reqTs_);
      }
      if (rspTs_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
                .computeUInt64Size(9, rspTs_);
      }
      if (accessFilePosition_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
                .computeUInt64Size(10, accessFilePosition_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof com.laiyz.proto.SenderMsg.Rsp)) {
        return super.equals(obj);
      }
      com.laiyz.proto.SenderMsg.Rsp other = (com.laiyz.proto.SenderMsg.Rsp) obj;

      if (!getId()
              .equals(other.getId())) return false;
      if (!getCmd()
              .equals(other.getCmd())) return false;
      if (!getFilepath()
              .equals(other.getFilepath())) return false;
      if (getFileSize()
              != other.getFileSize()) return false;
      if (!getChecksum()
              .equals(other.getChecksum())) return false;
      if (getRecvSize()
              != other.getRecvSize()) return false;
      if (getCurrRecvSize()
              != other.getCurrRecvSize()) return false;
      if (getReqTs()
              != other.getReqTs()) return false;
      if (getRspTs()
              != other.getRspTs()) return false;
      if (getAccessFilePosition()
              != other.getAccessFilePosition()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + CMD_FIELD_NUMBER;
      hash = (53 * hash) + getCmd().hashCode();
      hash = (37 * hash) + FILEPATH_FIELD_NUMBER;
      hash = (53 * hash) + getFilepath().hashCode();
      hash = (37 * hash) + FILESIZE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
              getFileSize());
      hash = (37 * hash) + CHECKSUM_FIELD_NUMBER;
      hash = (53 * hash) + getChecksum().hashCode();
      hash = (37 * hash) + RECVSIZE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
              getRecvSize());
      hash = (37 * hash) + CURRRECVSIZE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
              getCurrRecvSize());
      hash = (37 * hash) + REQTS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
              getReqTs());
      hash = (37 * hash) + RSPTS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
              getRspTs());
      hash = (37 * hash) + ACCESSFILEPOSITION_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
              getAccessFilePosition());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.laiyz.proto.SenderMsg.Rsp parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.laiyz.proto.SenderMsg.Rsp parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.laiyz.proto.SenderMsg.Rsp parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.laiyz.proto.SenderMsg.Rsp parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.laiyz.proto.SenderMsg.Rsp parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.laiyz.proto.SenderMsg.Rsp parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.laiyz.proto.SenderMsg.Rsp parseFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }
    public static com.laiyz.proto.SenderMsg.Rsp parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.laiyz.proto.SenderMsg.Rsp parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.laiyz.proto.SenderMsg.Rsp parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.laiyz.proto.SenderMsg.Rsp parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }
    public static com.laiyz.proto.SenderMsg.Rsp parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.laiyz.proto.SenderMsg.Rsp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
              ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.laiyz.proto.Rsp}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:com.laiyz.proto.Rsp)
            com.laiyz.proto.SenderMsg.RspOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return com.laiyz.proto.SenderMsg.internal_static_com_laiyz_proto_Rsp_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
        return com.laiyz.proto.SenderMsg.internal_static_com_laiyz_proto_Rsp_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        com.laiyz.proto.SenderMsg.Rsp.class, com.laiyz.proto.SenderMsg.Rsp.Builder.class);
      }

      // Construct using com.laiyz.proto.SenderMsg.Rsp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
              com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = "";

        cmd_ = "";

        filepath_ = "";

        fileSize_ = 0L;

        checksum_ = "";

        recvSize_ = 0L;

        currRecvSize_ = 0L;

        reqTs_ = 0L;

        rspTs_ = 0L;

        accessFilePosition_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
      getDescriptorForType() {
        return com.laiyz.proto.SenderMsg.internal_static_com_laiyz_proto_Rsp_descriptor;
      }

      @java.lang.Override
      public com.laiyz.proto.SenderMsg.Rsp getDefaultInstanceForType() {
        return com.laiyz.proto.SenderMsg.Rsp.getDefaultInstance();
      }

      @java.lang.Override
      public com.laiyz.proto.SenderMsg.Rsp build() {
        com.laiyz.proto.SenderMsg.Rsp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.laiyz.proto.SenderMsg.Rsp buildPartial() {
        com.laiyz.proto.SenderMsg.Rsp result = new com.laiyz.proto.SenderMsg.Rsp(this);
        result.id_ = id_;
        result.cmd_ = cmd_;
        result.filepath_ = filepath_;
        result.fileSize_ = fileSize_;
        result.checksum_ = checksum_;
        result.recvSize_ = recvSize_;
        result.currRecvSize_ = currRecvSize_;
        result.reqTs_ = reqTs_;
        result.rspTs_ = rspTs_;
        result.accessFilePosition_ = accessFilePosition_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
              com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
              com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.laiyz.proto.SenderMsg.Rsp) {
          return mergeFrom((com.laiyz.proto.SenderMsg.Rsp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.laiyz.proto.SenderMsg.Rsp other) {
        if (other == com.laiyz.proto.SenderMsg.Rsp.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (!other.getCmd().isEmpty()) {
          cmd_ = other.cmd_;
          onChanged();
        }
        if (!other.getFilepath().isEmpty()) {
          filepath_ = other.filepath_;
          onChanged();
        }
        if (other.getFileSize() != 0L) {
          setFileSize(other.getFileSize());
        }
        if (!other.getChecksum().isEmpty()) {
          checksum_ = other.checksum_;
          onChanged();
        }
        if (other.getRecvSize() != 0L) {
          setRecvSize(other.getRecvSize());
        }
        if (other.getCurrRecvSize() != 0L) {
          setCurrRecvSize(other.getCurrRecvSize());
        }
        if (other.getReqTs() != 0L) {
          setReqTs(other.getReqTs());
        }
        if (other.getRspTs() != 0L) {
          setRspTs(other.getRspTs());
        }
        if (other.getAccessFilePosition() != 0L) {
          setAccessFilePosition(other.getAccessFilePosition());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        com.laiyz.proto.SenderMsg.Rsp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.laiyz.proto.SenderMsg.Rsp) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       * @return The id.
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
      getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {

        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object cmd_ = "";
      /**
       * <code>string cmd = 2;</code>
       * @return The cmd.
       */
      public java.lang.String getCmd() {
        java.lang.Object ref = cmd_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          cmd_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string cmd = 2;</code>
       * @return The bytes for cmd.
       */
      public com.google.protobuf.ByteString
      getCmdBytes() {
        java.lang.Object ref = cmd_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          cmd_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string cmd = 2;</code>
       * @param value The cmd to set.
       * @return This builder for chaining.
       */
      public Builder setCmd(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        cmd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string cmd = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCmd() {

        cmd_ = getDefaultInstance().getCmd();
        onChanged();
        return this;
      }
      /**
       * <code>string cmd = 2;</code>
       * @param value The bytes for cmd to set.
       * @return This builder for chaining.
       */
      public Builder setCmdBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        cmd_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object filepath_ = "";
      /**
       * <code>string filepath = 3;</code>
       * @return The filepath.
       */
      public java.lang.String getFilepath() {
        java.lang.Object ref = filepath_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          filepath_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string filepath = 3;</code>
       * @return The bytes for filepath.
       */
      public com.google.protobuf.ByteString
      getFilepathBytes() {
        java.lang.Object ref = filepath_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          filepath_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string filepath = 3;</code>
       * @param value The filepath to set.
       * @return This builder for chaining.
       */
      public Builder setFilepath(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        filepath_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string filepath = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearFilepath() {

        filepath_ = getDefaultInstance().getFilepath();
        onChanged();
        return this;
      }
      /**
       * <code>string filepath = 3;</code>
       * @param value The bytes for filepath to set.
       * @return This builder for chaining.
       */
      public Builder setFilepathBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        filepath_ = value;
        onChanged();
        return this;
      }

      private long fileSize_ ;
      /**
       * <code>uint64 fileSize = 4;</code>
       * @return The fileSize.
       */
      public long getFileSize() {
        return fileSize_;
      }
      /**
       * <code>uint64 fileSize = 4;</code>
       * @param value The fileSize to set.
       * @return This builder for chaining.
       */
      public Builder setFileSize(long value) {

        fileSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 fileSize = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearFileSize() {

        fileSize_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object checksum_ = "";
      /**
       * <code>string checksum = 5;</code>
       * @return The checksum.
       */
      public java.lang.String getChecksum() {
        java.lang.Object ref = checksum_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          checksum_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string checksum = 5;</code>
       * @return The bytes for checksum.
       */
      public com.google.protobuf.ByteString
      getChecksumBytes() {
        java.lang.Object ref = checksum_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          checksum_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string checksum = 5;</code>
       * @param value The checksum to set.
       * @return This builder for chaining.
       */
      public Builder setChecksum(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        checksum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string checksum = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearChecksum() {

        checksum_ = getDefaultInstance().getChecksum();
        onChanged();
        return this;
      }
      /**
       * <code>string checksum = 5;</code>
       * @param value The bytes for checksum to set.
       * @return This builder for chaining.
       */
      public Builder setChecksumBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        checksum_ = value;
        onChanged();
        return this;
      }

      private long recvSize_ ;
      /**
       * <code>uint64 recvSize = 6;</code>
       * @return The recvSize.
       */
      public long getRecvSize() {
        return recvSize_;
      }
      /**
       * <code>uint64 recvSize = 6;</code>
       * @param value The recvSize to set.
       * @return This builder for chaining.
       */
      public Builder setRecvSize(long value) {

        recvSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 recvSize = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearRecvSize() {

        recvSize_ = 0L;
        onChanged();
        return this;
      }

      private long currRecvSize_ ;
      /**
       * <code>uint64 currRecvSize = 7;</code>
       * @return The currRecvSize.
       */
      public long getCurrRecvSize() {
        return currRecvSize_;
      }
      /**
       * <code>uint64 currRecvSize = 7;</code>
       * @param value The currRecvSize to set.
       * @return This builder for chaining.
       */
      public Builder setCurrRecvSize(long value) {

        currRecvSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 currRecvSize = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearCurrRecvSize() {

        currRecvSize_ = 0L;
        onChanged();
        return this;
      }

      private long reqTs_ ;
      /**
       * <code>uint64 reqTs = 8;</code>
       * @return The reqTs.
       */
      public long getReqTs() {
        return reqTs_;
      }
      /**
       * <code>uint64 reqTs = 8;</code>
       * @param value The reqTs to set.
       * @return This builder for chaining.
       */
      public Builder setReqTs(long value) {

        reqTs_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 reqTs = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearReqTs() {

        reqTs_ = 0L;
        onChanged();
        return this;
      }

      private long rspTs_ ;
      /**
       * <code>uint64 rspTs = 9;</code>
       * @return The rspTs.
       */
      public long getRspTs() {
        return rspTs_;
      }
      /**
       * <code>uint64 rspTs = 9;</code>
       * @param value The rspTs to set.
       * @return This builder for chaining.
       */
      public Builder setRspTs(long value) {

        rspTs_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 rspTs = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearRspTs() {

        rspTs_ = 0L;
        onChanged();
        return this;
      }

      private long accessFilePosition_ ;
      /**
       * <code>uint64 accessFilePosition = 10;</code>
       * @return The accessFilePosition.
       */
      public long getAccessFilePosition() {
        return accessFilePosition_;
      }
      /**
       * <code>uint64 accessFilePosition = 10;</code>
       * @param value The accessFilePosition to set.
       * @return This builder for chaining.
       */
      public Builder setAccessFilePosition(long value) {

        accessFilePosition_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 accessFilePosition = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearAccessFilePosition() {

        accessFilePosition_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.laiyz.proto.Rsp)
    }

    // @@protoc_insertion_point(class_scope:com.laiyz.proto.Rsp)
    private static final com.laiyz.proto.SenderMsg.Rsp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.laiyz.proto.SenderMsg.Rsp();
    }

    public static com.laiyz.proto.SenderMsg.Rsp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Rsp>
            PARSER = new com.google.protobuf.AbstractParser<Rsp>() {
      @java.lang.Override
      public Rsp parsePartialFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return new Rsp(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Rsp> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Rsp> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.laiyz.proto.SenderMsg.Rsp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
          internal_static_com_laiyz_proto_Req_descriptor;
  private static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internal_static_com_laiyz_proto_Req_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
          internal_static_com_laiyz_proto_Rsp_descriptor;
  private static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internal_static_com_laiyz_proto_Rsp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
  getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
          descriptor;
  static {
    java.lang.String[] descriptorData = {
            "\n\017SenderMsg.proto\022\017com.laiyz.proto\"X\n\003Re" +
                    "q\022\n\n\002id\030\001 \001(\t\022\013\n\003cmd\030\002 \001(\t\022\020\n\010filepath\030\003" +
                    " \001(\t\022\n\n\002ts\030\004 \001(\004\022\032\n\022accessFilePosition\030\005" +
                    " \001(\004\"\266\001\n\003Rsp\022\n\n\002id\030\001 \001(\t\022\013\n\003cmd\030\002 \001(\t\022\020\n" +
                    "\010filepath\030\003 \001(\t\022\020\n\010fileSize\030\004 \001(\004\022\020\n\010che" +
                    "cksum\030\005 \001(\t\022\020\n\010recvSize\030\006 \001(\004\022\024\n\014currRec" +
                    "vSize\030\007 \001(\004\022\r\n\005reqTs\030\010 \001(\004\022\r\n\005rspTs\030\t \001(" +
                    "\004\022\032\n\022accessFilePosition\030\n \001(\004B\036\n\017com.lai" +
                    "yz.protoB\tSenderMsgH\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
            .internalBuildGeneratedFileFrom(descriptorData,
                    new com.google.protobuf.Descriptors.FileDescriptor[] {
                    });
    internal_static_com_laiyz_proto_Req_descriptor =
            getDescriptor().getMessageTypes().get(0);
    internal_static_com_laiyz_proto_Req_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_com_laiyz_proto_Req_descriptor,
            new java.lang.String[] { "Id", "Cmd", "Filepath", "Ts", "AccessFilePosition", });
    internal_static_com_laiyz_proto_Rsp_descriptor =
            getDescriptor().getMessageTypes().get(1);
    internal_static_com_laiyz_proto_Rsp_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_com_laiyz_proto_Rsp_descriptor,
            new java.lang.String[] { "Id", "Cmd", "Filepath", "FileSize", "Checksum", "RecvSize", "CurrRecvSize", "ReqTs", "RspTs", "AccessFilePosition", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
