// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SenderMsg.proto

package com.laiyz.proto;

public final class SenderMsg {
  private SenderMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.laiyz.proto.Req)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>string cmd = 2;</code>
     * @return The cmd.
     */
    java.lang.String getCmd();
    /**
     * <code>string cmd = 2;</code>
     * @return The bytes for cmd.
     */
    com.google.protobuf.ByteString
        getCmdBytes();

    /**
     * <code>string filepath = 3;</code>
     * @return The filepath.
     */
    java.lang.String getFilepath();
    /**
     * <code>string filepath = 3;</code>
     * @return The bytes for filepath.
     */
    com.google.protobuf.ByteString
        getFilepathBytes();

    /**
     * <code>uint64 ts = 4;</code>
     * @return The ts.
     */
    long getTs();
  }
  /**
   * Protobuf type {@code com.laiyz.proto.Req}
   */
  public static final class Req extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.laiyz.proto.Req)
      ReqOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Req.newBuilder() to construct.
    private Req(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Req() {
      id_ = "";
      cmd_ = "";
      filepath_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Req();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.laiyz.proto.SenderMsg.internal_static_com_laiyz_proto_Req_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.laiyz.proto.SenderMsg.internal_static_com_laiyz_proto_Req_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.laiyz.proto.SenderMsg.Req.class, com.laiyz.proto.SenderMsg.Req.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object id_ = "";
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CMD_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object cmd_ = "";
    /**
     * <code>string cmd = 2;</code>
     * @return The cmd.
     */
    @java.lang.Override
    public java.lang.String getCmd() {
      java.lang.Object ref = cmd_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cmd_ = s;
        return s;
      }
    }
    /**
     * <code>string cmd = 2;</code>
     * @return The bytes for cmd.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCmdBytes() {
      java.lang.Object ref = cmd_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cmd_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FILEPATH_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object filepath_ = "";
    /**
     * <code>string filepath = 3;</code>
     * @return The filepath.
     */
    @java.lang.Override
    public java.lang.String getFilepath() {
      java.lang.Object ref = filepath_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        filepath_ = s;
        return s;
      }
    }
    /**
     * <code>string filepath = 3;</code>
     * @return The bytes for filepath.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFilepathBytes() {
      java.lang.Object ref = filepath_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        filepath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TS_FIELD_NUMBER = 4;
    private long ts_ = 0L;
    /**
     * <code>uint64 ts = 4;</code>
     * @return The ts.
     */
    @java.lang.Override
    public long getTs() {
      return ts_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (!getCmdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, cmd_);
      }
      if (!getFilepathBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, filepath_);
      }
      if (ts_ != 0L) {
        output.writeUInt64(4, ts_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (!getCmdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, cmd_);
      }
      if (!getFilepathBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, filepath_);
      }
      if (ts_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, ts_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.laiyz.proto.SenderMsg.Req)) {
        return super.equals(obj);
      }
      com.laiyz.proto.SenderMsg.Req other = (com.laiyz.proto.SenderMsg.Req) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (!getCmd()
          .equals(other.getCmd())) return false;
      if (!getFilepath()
          .equals(other.getFilepath())) return false;
      if (getTs()
          != other.getTs()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + CMD_FIELD_NUMBER;
      hash = (53 * hash) + getCmd().hashCode();
      hash = (37 * hash) + FILEPATH_FIELD_NUMBER;
      hash = (53 * hash) + getFilepath().hashCode();
      hash = (37 * hash) + TS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTs());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.laiyz.proto.SenderMsg.Req parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.laiyz.proto.SenderMsg.Req parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.laiyz.proto.SenderMsg.Req parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.laiyz.proto.SenderMsg.Req parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.laiyz.proto.SenderMsg.Req parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.laiyz.proto.SenderMsg.Req parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.laiyz.proto.SenderMsg.Req parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.laiyz.proto.SenderMsg.Req parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.laiyz.proto.SenderMsg.Req parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.laiyz.proto.SenderMsg.Req parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.laiyz.proto.SenderMsg.Req parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.laiyz.proto.SenderMsg.Req parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.laiyz.proto.SenderMsg.Req prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.laiyz.proto.Req}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.laiyz.proto.Req)
        com.laiyz.proto.SenderMsg.ReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.laiyz.proto.SenderMsg.internal_static_com_laiyz_proto_Req_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.laiyz.proto.SenderMsg.internal_static_com_laiyz_proto_Req_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.laiyz.proto.SenderMsg.Req.class, com.laiyz.proto.SenderMsg.Req.Builder.class);
      }

      // Construct using com.laiyz.proto.SenderMsg.Req.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = "";
        cmd_ = "";
        filepath_ = "";
        ts_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.laiyz.proto.SenderMsg.internal_static_com_laiyz_proto_Req_descriptor;
      }

      @java.lang.Override
      public com.laiyz.proto.SenderMsg.Req getDefaultInstanceForType() {
        return com.laiyz.proto.SenderMsg.Req.getDefaultInstance();
      }

      @java.lang.Override
      public com.laiyz.proto.SenderMsg.Req build() {
        com.laiyz.proto.SenderMsg.Req result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.laiyz.proto.SenderMsg.Req buildPartial() {
        com.laiyz.proto.SenderMsg.Req result = new com.laiyz.proto.SenderMsg.Req(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.laiyz.proto.SenderMsg.Req result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.cmd_ = cmd_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.filepath_ = filepath_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.ts_ = ts_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.laiyz.proto.SenderMsg.Req) {
          return mergeFrom((com.laiyz.proto.SenderMsg.Req)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.laiyz.proto.SenderMsg.Req other) {
        if (other == com.laiyz.proto.SenderMsg.Req.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getCmd().isEmpty()) {
          cmd_ = other.cmd_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getFilepath().isEmpty()) {
          filepath_ = other.filepath_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (other.getTs() != 0L) {
          setTs(other.getTs());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                id_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                cmd_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                filepath_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 32: {
                ts_ = input.readUInt64();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              default: {
//                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
//                  done = true; // was an endgroup tag
//                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       * @return The id.
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        id_ = getDefaultInstance().getId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object cmd_ = "";
      /**
       * <code>string cmd = 2;</code>
       * @return The cmd.
       */
      public java.lang.String getCmd() {
        java.lang.Object ref = cmd_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          cmd_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string cmd = 2;</code>
       * @return The bytes for cmd.
       */
      public com.google.protobuf.ByteString
          getCmdBytes() {
        java.lang.Object ref = cmd_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cmd_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string cmd = 2;</code>
       * @param value The cmd to set.
       * @return This builder for chaining.
       */
      public Builder setCmd(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        cmd_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string cmd = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCmd() {
        cmd_ = getDefaultInstance().getCmd();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string cmd = 2;</code>
       * @param value The bytes for cmd to set.
       * @return This builder for chaining.
       */
      public Builder setCmdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        cmd_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object filepath_ = "";
      /**
       * <code>string filepath = 3;</code>
       * @return The filepath.
       */
      public java.lang.String getFilepath() {
        java.lang.Object ref = filepath_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          filepath_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string filepath = 3;</code>
       * @return The bytes for filepath.
       */
      public com.google.protobuf.ByteString
          getFilepathBytes() {
        java.lang.Object ref = filepath_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          filepath_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string filepath = 3;</code>
       * @param value The filepath to set.
       * @return This builder for chaining.
       */
      public Builder setFilepath(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        filepath_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string filepath = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearFilepath() {
        filepath_ = getDefaultInstance().getFilepath();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string filepath = 3;</code>
       * @param value The bytes for filepath to set.
       * @return This builder for chaining.
       */
      public Builder setFilepathBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        filepath_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private long ts_ ;
      /**
       * <code>uint64 ts = 4;</code>
       * @return The ts.
       */
      @java.lang.Override
      public long getTs() {
        return ts_;
      }
      /**
       * <code>uint64 ts = 4;</code>
       * @param value The ts to set.
       * @return This builder for chaining.
       */
      public Builder setTs(long value) {
        
        ts_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 ts = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearTs() {
        bitField0_ = (bitField0_ & ~0x00000008);
        ts_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.laiyz.proto.Req)
    }

    // @@protoc_insertion_point(class_scope:com.laiyz.proto.Req)
    private static final com.laiyz.proto.SenderMsg.Req DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.laiyz.proto.SenderMsg.Req();
    }

    public static com.laiyz.proto.SenderMsg.Req getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Req>
        PARSER = new com.google.protobuf.AbstractParser<Req>() {
      @java.lang.Override
      public Req parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Req> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Req> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.laiyz.proto.SenderMsg.Req getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RspOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.laiyz.proto.Rsp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>string cmd = 2;</code>
     * @return The cmd.
     */
    java.lang.String getCmd();
    /**
     * <code>string cmd = 2;</code>
     * @return The bytes for cmd.
     */
    com.google.protobuf.ByteString
        getCmdBytes();

    /**
     * <code>string filepath = 3;</code>
     * @return The filepath.
     */
    java.lang.String getFilepath();
    /**
     * <code>string filepath = 3;</code>
     * @return The bytes for filepath.
     */
    com.google.protobuf.ByteString
        getFilepathBytes();

    /**
     * <code>uint64 fileSize = 4;</code>
     * @return The fileSize.
     */
    long getFileSize();

    /**
     * <code>string checksum = 5;</code>
     * @return The checksum.
     */
    java.lang.String getChecksum();
    /**
     * <code>string checksum = 5;</code>
     * @return The bytes for checksum.
     */
    com.google.protobuf.ByteString
        getChecksumBytes();

    /**
     * <code>string rspData = 6;</code>
     * @return The rspData.
     */
    java.lang.String getRspData();
    /**
     * <code>string rspData = 6;</code>
     * @return The bytes for rspData.
     */
    com.google.protobuf.ByteString
        getRspDataBytes();

    /**
     * <code>bytes chunkData = 7;</code>
     * @return The chunkData.
     */
    com.google.protobuf.ByteString getChunkData();

    /**
     * <code>uint64 reqTs = 8;</code>
     * @return The reqTs.
     */
    long getReqTs();

    /**
     * <code>uint64 rspTs = 9;</code>
     * @return The rspTs.
     */
    long getRspTs();

    /**
     * <code>uint64 accessFilePosition = 10;</code>
     * @return The accessFilePosition.
     */
    long getAccessFilePosition();
  }
  /**
   * Protobuf type {@code com.laiyz.proto.Rsp}
   */
  public static final class Rsp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.laiyz.proto.Rsp)
      RspOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Rsp.newBuilder() to construct.
    private Rsp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Rsp() {
      id_ = "";
      cmd_ = "";
      filepath_ = "";
      checksum_ = "";
      rspData_ = "";
      chunkData_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Rsp();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.laiyz.proto.SenderMsg.internal_static_com_laiyz_proto_Rsp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.laiyz.proto.SenderMsg.internal_static_com_laiyz_proto_Rsp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.laiyz.proto.SenderMsg.Rsp.class, com.laiyz.proto.SenderMsg.Rsp.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object id_ = "";
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CMD_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object cmd_ = "";
    /**
     * <code>string cmd = 2;</code>
     * @return The cmd.
     */
    @java.lang.Override
    public java.lang.String getCmd() {
      java.lang.Object ref = cmd_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cmd_ = s;
        return s;
      }
    }
    /**
     * <code>string cmd = 2;</code>
     * @return The bytes for cmd.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCmdBytes() {
      java.lang.Object ref = cmd_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cmd_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FILEPATH_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object filepath_ = "";
    /**
     * <code>string filepath = 3;</code>
     * @return The filepath.
     */
    @java.lang.Override
    public java.lang.String getFilepath() {
      java.lang.Object ref = filepath_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        filepath_ = s;
        return s;
      }
    }
    /**
     * <code>string filepath = 3;</code>
     * @return The bytes for filepath.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFilepathBytes() {
      java.lang.Object ref = filepath_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        filepath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FILESIZE_FIELD_NUMBER = 4;
    private long fileSize_ = 0L;
    /**
     * <code>uint64 fileSize = 4;</code>
     * @return The fileSize.
     */
    @java.lang.Override
    public long getFileSize() {
      return fileSize_;
    }

    public static final int CHECKSUM_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile java.lang.Object checksum_ = "";
    /**
     * <code>string checksum = 5;</code>
     * @return The checksum.
     */
    @java.lang.Override
    public java.lang.String getChecksum() {
      java.lang.Object ref = checksum_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        checksum_ = s;
        return s;
      }
    }
    /**
     * <code>string checksum = 5;</code>
     * @return The bytes for checksum.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getChecksumBytes() {
      java.lang.Object ref = checksum_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        checksum_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RSPDATA_FIELD_NUMBER = 6;
    @SuppressWarnings("serial")
    private volatile java.lang.Object rspData_ = "";
    /**
     * <code>string rspData = 6;</code>
     * @return The rspData.
     */
    @java.lang.Override
    public java.lang.String getRspData() {
      java.lang.Object ref = rspData_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        rspData_ = s;
        return s;
      }
    }
    /**
     * <code>string rspData = 6;</code>
     * @return The bytes for rspData.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRspDataBytes() {
      java.lang.Object ref = rspData_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        rspData_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CHUNKDATA_FIELD_NUMBER = 7;
    private com.google.protobuf.ByteString chunkData_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes chunkData = 7;</code>
     * @return The chunkData.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getChunkData() {
      return chunkData_;
    }

    public static final int REQTS_FIELD_NUMBER = 8;
    private long reqTs_ = 0L;
    /**
     * <code>uint64 reqTs = 8;</code>
     * @return The reqTs.
     */
    @java.lang.Override
    public long getReqTs() {
      return reqTs_;
    }

    public static final int RSPTS_FIELD_NUMBER = 9;
    private long rspTs_ = 0L;
    /**
     * <code>uint64 rspTs = 9;</code>
     * @return The rspTs.
     */
    @java.lang.Override
    public long getRspTs() {
      return rspTs_;
    }

    public static final int ACCESSFILEPOSITION_FIELD_NUMBER = 10;
    private long accessFilePosition_ = 0L;
    /**
     * <code>uint64 accessFilePosition = 10;</code>
     * @return The accessFilePosition.
     */
    @java.lang.Override
    public long getAccessFilePosition() {
      return accessFilePosition_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (!getCmdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, cmd_);
      }
      if (!getFilepathBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, filepath_);
      }
      if (fileSize_ != 0L) {
        output.writeUInt64(4, fileSize_);
      }
      if (!getChecksumBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, checksum_);
      }
      if (!getRspDataBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, rspData_);
      }
      if (!chunkData_.isEmpty()) {
        output.writeBytes(7, chunkData_);
      }
      if (reqTs_ != 0L) {
        output.writeUInt64(8, reqTs_);
      }
      if (rspTs_ != 0L) {
        output.writeUInt64(9, rspTs_);
      }
      if (accessFilePosition_ != 0L) {
        output.writeUInt64(10, accessFilePosition_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (!getCmdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, cmd_);
      }
      if (!getFilepathBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, filepath_);
      }
      if (fileSize_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, fileSize_);
      }
      if (!getChecksumBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, checksum_);
      }
      if (!getRspDataBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, rspData_);
      }
      if (!chunkData_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, chunkData_);
      }
      if (reqTs_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(8, reqTs_);
      }
      if (rspTs_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(9, rspTs_);
      }
      if (accessFilePosition_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(10, accessFilePosition_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.laiyz.proto.SenderMsg.Rsp)) {
        return super.equals(obj);
      }
      com.laiyz.proto.SenderMsg.Rsp other = (com.laiyz.proto.SenderMsg.Rsp) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (!getCmd()
          .equals(other.getCmd())) return false;
      if (!getFilepath()
          .equals(other.getFilepath())) return false;
      if (getFileSize()
          != other.getFileSize()) return false;
      if (!getChecksum()
          .equals(other.getChecksum())) return false;
      if (!getRspData()
          .equals(other.getRspData())) return false;
      if (!getChunkData()
          .equals(other.getChunkData())) return false;
      if (getReqTs()
          != other.getReqTs()) return false;
      if (getRspTs()
          != other.getRspTs()) return false;
      if (getAccessFilePosition()
          != other.getAccessFilePosition()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + CMD_FIELD_NUMBER;
      hash = (53 * hash) + getCmd().hashCode();
      hash = (37 * hash) + FILEPATH_FIELD_NUMBER;
      hash = (53 * hash) + getFilepath().hashCode();
      hash = (37 * hash) + FILESIZE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getFileSize());
      hash = (37 * hash) + CHECKSUM_FIELD_NUMBER;
      hash = (53 * hash) + getChecksum().hashCode();
      hash = (37 * hash) + RSPDATA_FIELD_NUMBER;
      hash = (53 * hash) + getRspData().hashCode();
      hash = (37 * hash) + CHUNKDATA_FIELD_NUMBER;
      hash = (53 * hash) + getChunkData().hashCode();
      hash = (37 * hash) + REQTS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getReqTs());
      hash = (37 * hash) + RSPTS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRspTs());
      hash = (37 * hash) + ACCESSFILEPOSITION_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getAccessFilePosition());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.laiyz.proto.SenderMsg.Rsp parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.laiyz.proto.SenderMsg.Rsp parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.laiyz.proto.SenderMsg.Rsp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.laiyz.proto.SenderMsg.Rsp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.laiyz.proto.SenderMsg.Rsp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.laiyz.proto.SenderMsg.Rsp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.laiyz.proto.SenderMsg.Rsp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.laiyz.proto.SenderMsg.Rsp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.laiyz.proto.SenderMsg.Rsp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.laiyz.proto.SenderMsg.Rsp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.laiyz.proto.SenderMsg.Rsp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.laiyz.proto.SenderMsg.Rsp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.laiyz.proto.SenderMsg.Rsp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.laiyz.proto.Rsp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.laiyz.proto.Rsp)
        com.laiyz.proto.SenderMsg.RspOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.laiyz.proto.SenderMsg.internal_static_com_laiyz_proto_Rsp_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.laiyz.proto.SenderMsg.internal_static_com_laiyz_proto_Rsp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.laiyz.proto.SenderMsg.Rsp.class, com.laiyz.proto.SenderMsg.Rsp.Builder.class);
      }

      // Construct using com.laiyz.proto.SenderMsg.Rsp.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = "";
        cmd_ = "";
        filepath_ = "";
        fileSize_ = 0L;
        checksum_ = "";
        rspData_ = "";
        chunkData_ = com.google.protobuf.ByteString.EMPTY;
        reqTs_ = 0L;
        rspTs_ = 0L;
        accessFilePosition_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.laiyz.proto.SenderMsg.internal_static_com_laiyz_proto_Rsp_descriptor;
      }

      @java.lang.Override
      public com.laiyz.proto.SenderMsg.Rsp getDefaultInstanceForType() {
        return com.laiyz.proto.SenderMsg.Rsp.getDefaultInstance();
      }

      @java.lang.Override
      public com.laiyz.proto.SenderMsg.Rsp build() {
        com.laiyz.proto.SenderMsg.Rsp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.laiyz.proto.SenderMsg.Rsp buildPartial() {
        com.laiyz.proto.SenderMsg.Rsp result = new com.laiyz.proto.SenderMsg.Rsp(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.laiyz.proto.SenderMsg.Rsp result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.cmd_ = cmd_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.filepath_ = filepath_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.fileSize_ = fileSize_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.checksum_ = checksum_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.rspData_ = rspData_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.chunkData_ = chunkData_;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.reqTs_ = reqTs_;
        }
        if (((from_bitField0_ & 0x00000100) != 0)) {
          result.rspTs_ = rspTs_;
        }
        if (((from_bitField0_ & 0x00000200) != 0)) {
          result.accessFilePosition_ = accessFilePosition_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.laiyz.proto.SenderMsg.Rsp) {
          return mergeFrom((com.laiyz.proto.SenderMsg.Rsp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.laiyz.proto.SenderMsg.Rsp other) {
        if (other == com.laiyz.proto.SenderMsg.Rsp.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getCmd().isEmpty()) {
          cmd_ = other.cmd_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getFilepath().isEmpty()) {
          filepath_ = other.filepath_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (other.getFileSize() != 0L) {
          setFileSize(other.getFileSize());
        }
        if (!other.getChecksum().isEmpty()) {
          checksum_ = other.checksum_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        if (!other.getRspData().isEmpty()) {
          rspData_ = other.rspData_;
          bitField0_ |= 0x00000020;
          onChanged();
        }
        if (other.getChunkData() != com.google.protobuf.ByteString.EMPTY) {
          setChunkData(other.getChunkData());
        }
        if (other.getReqTs() != 0L) {
          setReqTs(other.getReqTs());
        }
        if (other.getRspTs() != 0L) {
          setRspTs(other.getRspTs());
        }
        if (other.getAccessFilePosition() != 0L) {
          setAccessFilePosition(other.getAccessFilePosition());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                id_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                cmd_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                filepath_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 32: {
                fileSize_ = input.readUInt64();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 42: {
                checksum_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              case 50: {
                rspData_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              case 58: {
                chunkData_ = input.readBytes();
                bitField0_ |= 0x00000040;
                break;
              } // case 58
              case 64: {
                reqTs_ = input.readUInt64();
                bitField0_ |= 0x00000080;
                break;
              } // case 64
              case 72: {
                rspTs_ = input.readUInt64();
                bitField0_ |= 0x00000100;
                break;
              } // case 72
              case 80: {
                accessFilePosition_ = input.readUInt64();
                bitField0_ |= 0x00000200;
                break;
              } // case 80
              default: {
//                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
//                  done = true; // was an endgroup tag
//                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       * @return The id.
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        id_ = getDefaultInstance().getId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object cmd_ = "";
      /**
       * <code>string cmd = 2;</code>
       * @return The cmd.
       */
      public java.lang.String getCmd() {
        java.lang.Object ref = cmd_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          cmd_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string cmd = 2;</code>
       * @return The bytes for cmd.
       */
      public com.google.protobuf.ByteString
          getCmdBytes() {
        java.lang.Object ref = cmd_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cmd_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string cmd = 2;</code>
       * @param value The cmd to set.
       * @return This builder for chaining.
       */
      public Builder setCmd(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        cmd_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string cmd = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCmd() {
        cmd_ = getDefaultInstance().getCmd();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string cmd = 2;</code>
       * @param value The bytes for cmd to set.
       * @return This builder for chaining.
       */
      public Builder setCmdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        cmd_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object filepath_ = "";
      /**
       * <code>string filepath = 3;</code>
       * @return The filepath.
       */
      public java.lang.String getFilepath() {
        java.lang.Object ref = filepath_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          filepath_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string filepath = 3;</code>
       * @return The bytes for filepath.
       */
      public com.google.protobuf.ByteString
          getFilepathBytes() {
        java.lang.Object ref = filepath_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          filepath_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string filepath = 3;</code>
       * @param value The filepath to set.
       * @return This builder for chaining.
       */
      public Builder setFilepath(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        filepath_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string filepath = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearFilepath() {
        filepath_ = getDefaultInstance().getFilepath();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string filepath = 3;</code>
       * @param value The bytes for filepath to set.
       * @return This builder for chaining.
       */
      public Builder setFilepathBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        filepath_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private long fileSize_ ;
      /**
       * <code>uint64 fileSize = 4;</code>
       * @return The fileSize.
       */
      @java.lang.Override
      public long getFileSize() {
        return fileSize_;
      }
      /**
       * <code>uint64 fileSize = 4;</code>
       * @param value The fileSize to set.
       * @return This builder for chaining.
       */
      public Builder setFileSize(long value) {
        
        fileSize_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 fileSize = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearFileSize() {
        bitField0_ = (bitField0_ & ~0x00000008);
        fileSize_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object checksum_ = "";
      /**
       * <code>string checksum = 5;</code>
       * @return The checksum.
       */
      public java.lang.String getChecksum() {
        java.lang.Object ref = checksum_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          checksum_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string checksum = 5;</code>
       * @return The bytes for checksum.
       */
      public com.google.protobuf.ByteString
          getChecksumBytes() {
        java.lang.Object ref = checksum_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          checksum_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string checksum = 5;</code>
       * @param value The checksum to set.
       * @return This builder for chaining.
       */
      public Builder setChecksum(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        checksum_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>string checksum = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearChecksum() {
        checksum_ = getDefaultInstance().getChecksum();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>string checksum = 5;</code>
       * @param value The bytes for checksum to set.
       * @return This builder for chaining.
       */
      public Builder setChecksumBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        checksum_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      private java.lang.Object rspData_ = "";
      /**
       * <code>string rspData = 6;</code>
       * @return The rspData.
       */
      public java.lang.String getRspData() {
        java.lang.Object ref = rspData_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          rspData_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string rspData = 6;</code>
       * @return The bytes for rspData.
       */
      public com.google.protobuf.ByteString
          getRspDataBytes() {
        java.lang.Object ref = rspData_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          rspData_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string rspData = 6;</code>
       * @param value The rspData to set.
       * @return This builder for chaining.
       */
      public Builder setRspData(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        rspData_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>string rspData = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearRspData() {
        rspData_ = getDefaultInstance().getRspData();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <code>string rspData = 6;</code>
       * @param value The bytes for rspData to set.
       * @return This builder for chaining.
       */
      public Builder setRspDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        rspData_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString chunkData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes chunkData = 7;</code>
       * @return The chunkData.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getChunkData() {
        return chunkData_;
      }
      /**
       * <code>bytes chunkData = 7;</code>
       * @param value The chunkData to set.
       * @return This builder for chaining.
       */
      public Builder setChunkData(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        chunkData_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>bytes chunkData = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearChunkData() {
        bitField0_ = (bitField0_ & ~0x00000040);
        chunkData_ = getDefaultInstance().getChunkData();
        onChanged();
        return this;
      }

      private long reqTs_ ;
      /**
       * <code>uint64 reqTs = 8;</code>
       * @return The reqTs.
       */
      @java.lang.Override
      public long getReqTs() {
        return reqTs_;
      }
      /**
       * <code>uint64 reqTs = 8;</code>
       * @param value The reqTs to set.
       * @return This builder for chaining.
       */
      public Builder setReqTs(long value) {
        
        reqTs_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 reqTs = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearReqTs() {
        bitField0_ = (bitField0_ & ~0x00000080);
        reqTs_ = 0L;
        onChanged();
        return this;
      }

      private long rspTs_ ;
      /**
       * <code>uint64 rspTs = 9;</code>
       * @return The rspTs.
       */
      @java.lang.Override
      public long getRspTs() {
        return rspTs_;
      }
      /**
       * <code>uint64 rspTs = 9;</code>
       * @param value The rspTs to set.
       * @return This builder for chaining.
       */
      public Builder setRspTs(long value) {
        
        rspTs_ = value;
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 rspTs = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearRspTs() {
        bitField0_ = (bitField0_ & ~0x00000100);
        rspTs_ = 0L;
        onChanged();
        return this;
      }

      private long accessFilePosition_ ;
      /**
       * <code>uint64 accessFilePosition = 10;</code>
       * @return The accessFilePosition.
       */
      @java.lang.Override
      public long getAccessFilePosition() {
        return accessFilePosition_;
      }
      /**
       * <code>uint64 accessFilePosition = 10;</code>
       * @param value The accessFilePosition to set.
       * @return This builder for chaining.
       */
      public Builder setAccessFilePosition(long value) {
        
        accessFilePosition_ = value;
        bitField0_ |= 0x00000200;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 accessFilePosition = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearAccessFilePosition() {
        bitField0_ = (bitField0_ & ~0x00000200);
        accessFilePosition_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.laiyz.proto.Rsp)
    }

    // @@protoc_insertion_point(class_scope:com.laiyz.proto.Rsp)
    private static final com.laiyz.proto.SenderMsg.Rsp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.laiyz.proto.SenderMsg.Rsp();
    }

    public static com.laiyz.proto.SenderMsg.Rsp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Rsp>
        PARSER = new com.google.protobuf.AbstractParser<Rsp>() {
      @java.lang.Override
      public Rsp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Rsp> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Rsp> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.laiyz.proto.SenderMsg.Rsp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_laiyz_proto_Req_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_laiyz_proto_Req_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_laiyz_proto_Rsp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_laiyz_proto_Rsp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017SenderMsg.proto\022\017com.laiyz.proto\"<\n\003Re" +
      "q\022\n\n\002id\030\001 \001(\t\022\013\n\003cmd\030\002 \001(\t\022\020\n\010filepath\030\003" +
      " \001(\t\022\n\n\002ts\030\004 \001(\004\"\262\001\n\003Rsp\022\n\n\002id\030\001 \001(\t\022\013\n\003" +
      "cmd\030\002 \001(\t\022\020\n\010filepath\030\003 \001(\t\022\020\n\010fileSize\030" +
      "\004 \001(\004\022\020\n\010checksum\030\005 \001(\t\022\017\n\007rspData\030\006 \001(\t" +
      "\022\021\n\tchunkData\030\007 \001(\014\022\r\n\005reqTs\030\010 \001(\004\022\r\n\005rs" +
      "pTs\030\t \001(\004\022\032\n\022accessFilePosition\030\n \001(\004B\036\n" +
      "\017com.laiyz.protoB\tSenderMsgH\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_laiyz_proto_Req_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_laiyz_proto_Req_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_laiyz_proto_Req_descriptor,
        new java.lang.String[] { "Id", "Cmd", "Filepath", "Ts", });
    internal_static_com_laiyz_proto_Rsp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_laiyz_proto_Rsp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_laiyz_proto_Rsp_descriptor,
        new java.lang.String[] { "Id", "Cmd", "Filepath", "FileSize", "Checksum", "RspData", "ChunkData", "ReqTs", "RspTs", "AccessFilePosition", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
